callback_config:
  tensorboard_callback: true
common_config:
  base_config: /Users/chenhao/workspace/ConfigAI/examples/base_config.ini
  default_random_seed: 10
  eval_phase_list:
  - train
  - dev
  experiment_dir: /nfs/pony/chenhao/experiment
  is_overwrite_experiment: true
  is_save: true
  is_test: true
  is_train: true
  model_cls: CLSTokenClassifyModel
  model_name: cls_token_classify_example
  output_phase_list:
  - train
  - dev
  - test
  project_name: config_ai_example
  save_args:
    fmt: h5
compile_config:
  optimizer_args:
    learning_rate: 3.0e-05
  optimizer_name: adam
data_config:
  dev_data_path: /nfs/pony/chenhao/workspace/ConfigAI/data/sentiment_classify/labeled.jsonl
  test_data_path: /nfs/pony/chenhao/workspace/ConfigAI/data/sentiment_classify/labeled.jsonl
  train_data_path: /nfs/pony/chenhao/workspace/ConfigAI/data/sentiment_classify/labeled.jsonl
nn_model_config:
  pretrained_model_path: /nfs/pony/chenhao/pretrain/chinese_rbt4_L-4_H-768_A-12
  pretrained_model_tag: bert
task_config:
  label_path: /nfs/pony/chenhao/workspace/ConfigAI/data/sentiment_classify/labels.txt
  max_len: 128
  multi_label: false
test_config:
  batch_size: 64
  overwrite_cache: false
tokenizer_config:
  tokenizer_args:
    vocabs: /nfs/pony/chenhao/pretrain/chinese_rbt4_L-4_H-768_A-12/vocab.txt
  tokenizer_name: bert_word_piece
train_config:
  batch_size: 32
  epochs: 2
  overwrite_cache: false
  steps_per_epoch: 100
